In [35]:
import gymnasium as gym
import numpy as np
import sys

if "../" not in sys.path:
    sys.path.append("../")

from lib.envs.windy_gridworld import WindyGridworldEnv

In [43]:
env = WindyGridworldEnv()

state, _ = env.reset()
print("Initial state:", state)

env.render()

state, reward, done, truncated, info = env.step(1)
print(state, reward, done)
env.render()

state, reward, done, truncated, info = env.step(1)
print(state, reward, done)
env.render()

state, reward, done, truncated, info = env.step(1)
print(state, reward, done)
env.render()

state, reward, done, truncated, info = env.step(2)
print(state, reward, done)
env.render()

state, reward, done, truncated, info = env.step(1)
print(state, reward, done)
env.render()

state, reward, done, truncated, info = env.step(1)
print(state, reward, done, truncated, info)
env.render()

Initial state: 30
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
x  o  o  o  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

31 -1.0 False
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  x  o  o  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

32 -1.0 False
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  x  o  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

33 -1.0 False
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  x  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

33 -1.0 False
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  x  o  o  o  T 

# Sarsa Algorithm

In [48]:
import numpy as np
env = WindyGridworldEnv()
alpha = 0.5
gamma = 1.0
epsilon = 0.1
episodes = 200
Q = np.zeros((env.nS, env.nA))
print(Q)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0.

In [49]:
def epsilon_greedy(Q, state):
    m = np.random.rand()
    if m < epsilon:
        return np.random.randint(env.nA)
    else:
        return np.argmax(Q[state])

In [50]:
for episode in range(episodes):
    state,_ = env.reset()
    action = epsilon_greedy(Q,state)
    done = False
    while not done:
        next_state,reward,done,_,_ = env.step(action)
        next_action = epsilon_greedy(Q,next_state)
        Q[state,action] += alpha*(reward + gamma * Q[next_state,next_action]-Q[state,action])
        state = next_state
        action = next_action

In [51]:
print(Q)

[[-15.4685388  -15.49652208 -15.21384532 -15.18582321]
 [-15.20828581 -14.91974188 -15.25907234 -14.96818713]
 [-14.13549378 -14.13408806 -14.28434927 -14.28270925]
 [-13.63102596 -13.33139543 -13.53894259 -14.42758569]
 [-12.93631885 -12.7994203  -13.18082311 -13.05604723]
 [-12.30028638 -12.0595355  -12.13071303 -12.49616749]
 [-11.76987846 -10.84994712 -12.11738635 -12.5112169 ]
 [-11.40310409  -9.60110937 -11.27279461 -11.54012401]
 [ -9.66855747  -8.54900228 -10.45551602 -10.28476485]
 [ -9.19513386  -9.83064847  -6.77494221  -9.2289289 ]
 [-15.79624509 -15.51565062 -15.77999025 -15.81042469]
 [-15.35564158 -14.75677986 -15.37189402 -15.77324539]
 [-14.14973679 -13.93144117 -14.46655306 -14.77455253]
 [-13.19087191 -13.29759316 -13.54111249 -14.21827903]
 [-13.05858109 -12.08118508 -12.66078362 -13.90436529]
 [-12.35640534 -12.0082988  -12.14548447 -12.7823237 ]
 [-10.53184799 -10.11069848 -10.49880938 -11.69768025]
 [ -9.17525795  -9.08682375 -10.02345757  -9.35409842]
 [ -8.7148

In [33]:
policy = np.argmax(Q,axis=1)
print(policy.reshape(7,10))

[[1 1 1 1 1 1 1 1 1 2]
 [1 0 1 1 1 1 2 0 1 2]
 [1 1 1 1 1 1 1 0 1 2]
 [1 1 1 1 1 0 0 0 1 2]
 [1 1 1 1 0 0 0 2 3 3]
 [1 1 1 1 1 0 0 2 1 0]
 [1 0 3 1 0 0 0 0 3 3]]


In [30]:
state,_ = env.reset()
done = False
while not done:
    action = np.argmax(Q[state])
    state,reward,done,_,_ = env.step(action)
    env.render()

o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  x  o  o  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  x  o  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  x  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

o  o  o  o  o  o  o  o  o  o
o  o  o  x  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o

o  o  o  o  x  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  T  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o  o  o  o  o  o  o
o  o  o  o